### PR TITLE
Add finish setup panel

### PR DESCRIPTION
**Pull request by timarney**
### Testing

Create a new site called "template-site"(content will be pulled from here)

live site here https://articles.alpha.canada.ca/template-site/

- under the "template-site" ... create 2 pages 

1) home --- ensure the slug = `home`
2) maintenance --  --- ensure the slug = `maintenance`

=======================

Create another new site 

As a super admin visit the dashboard

You should see a new panel:
Screen Shot 2022-01-31 at 12 38 06 PM

Press the "Let's go" button

Wait for the status text to say finished 

After that visit *Site Settings*

- Mode =   Maintenance
- Homepage = home
- Maintenance = maintenance
- Search engine visibility = Discourage search engines  ...

Screen Shot 2022-01-31 at 12 40 25 PM

## Todo outside of this PR
- Create translations
- Create Posts
- Delete sample page

### CODE REVIEW

**Review by dsamojlenko — APPROVED** [review]
Looks great

**Comment by timarney** [comment]
ref: https://github.com/cds-snc/gc-articles-issues/issues/224

**Comment by timarney** [comment]
ref: https://github.com/cds-snc/gc-articles-issues/issues/167

**Comment by timarney** [comment]
Demo:
https://www.youtube.com/watch?v=NMU4cOGMqeo

**Pull request merged**
