### PR TITLE
Hide contact form for non super admin

### PR DESCRIPTION
**Pull request by timarney**
Follow up PR for:
https://github.com/cds-snc/gc-articles/pull/362

Only allow Super Admins to add a contact form

### CODE REVIEW

**Review by dsamojlenko — APPROVED** [review]

**Review by pcraig3 — COMMENTED** [review]
Can we customize the message here?

If I am an admin, this is what I see:

Screen Shot 2021-12-07 at 10 26 48

It's telling me that I should remove this block because it isn't supported, but it clearly _is_ working, I just don't have permissions to access it.

**Comment by timarney** [comment]
> Can we customize the message here?

No sure if we can customize that said --- I don't think we have any user / testers outside of ourselves that  dropped that in --- it's now an "internal form" vs a general contact form.

**Comment by timarney** [comment]
Going to merge but will look into how we can customize this type of message as we might need to do that in the future.

**Review by pcraig3 — APPROVED** [review]
Sounds good 👍 

Yeah, since local admins can't use it, it doesn't matter.

**Pull request merged**
